Repository gsoft-inc/wl-foundry-cli, pull requests merged in 2023-05, with the labels that each got.

#23 Disable Stylelint for project ;; WLFE-37
  .stylelintignore
Labels: build and tooling

#26 Make @workleap/create-project call npx correctly
  .changeset/shy-pens-compare.md
  packages/create-project/src/generateProject.ts
Labels: enhancement

#25 Write the OSS documentation ;; WLFE-29
  .github/ISSUE_TEMPLATE/01_bug.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  packages/create-project/README.md
  packages/create-project/package.json
  packages/foundry/package.json
  pnpm-lock.yaml
Labels: documentation

#27 New web-application template; WLFE-57
  .changeset/tough-doors-pretend.md
  package.json
  packages/create-project/src/bin.ts
  packages/create-project/src/generateProject.ts
  packages/create-project/src/templates.ts
  packages/foundry/README.md
  packages/foundry/src/bin.ts
  packages/foundry/src/create.ts
  pnpm-lock.yaml
  templates/web-application/.browserslistrc
  templates/web-application/.editorconfig
  templates/web-application/.eslintignore
  templates/web-application/.eslintrc.json
  templates/web-application/.gitattributes
  templates/web-application/.gitignore
  templates/web-application/.prettierignore
  templates/web-application/.stylelintignore
  templates/web-application/.stylelintrc.json
  templates/web-application/README.md
  templates/web-application/jest.config.js
  templates/web-application/loadSwcConfig.d.ts
  templates/web-application/loadSwcConfig.js
  templates/web-application/package.json
  templates/web-application/public/index.html
  templates/web-application/public/mockServiceWorker.js
  templates/web-application/src/App.tsx
  templates/web-application/src/Home.tsx
  templates/web-application/src/NoMatch.tsx
  templates/web-application/src/Office.tsx
  templates/web-application/src/RootErrorBoundary.tsx
  templates/web-application/src/RootLayout.tsx
  templates/web-application/src/components/Loading.test.tsx
  templates/web-application/src/components/Loading.tsx
  templates/web-application/src/components/TheAnswer.test.tsx
  templates/web-application/src/components/TheAnswer.tsx
  templates/web-application/src/index.css
  templates/web-application/src/index.tsx
  templates/web-application/src/mocks/browser.ts
  templates/web-application/src/mocks/handlers.ts
  templates/web-application/swc.build.js
  templates/web-application/swc.dev.js
  templates/web-application/tsconfig.json
  templates/web-application/webpack.build.js
  templates/web-application/webpack.dev.js
Labels: enhancement

#37 Add images support in `web-application` template ;; WLFE-60
  pnpm-lock.yaml
  templates/.gitignore
  templates/README.md
  templates/web-application/src/Office.tsx
  templates/web-application/src/assets/PngExample.tsx
  templates/web-application/src/assets/png_example.png
  templates/web-application/src/components/TheAnswer.tsx
  templates/web-application/src/typings/image.d.ts
Labels: enhancement, template

#38 Initialize MSW mock at the template creation
  packages/foundry/src/create.ts
  packages/foundry/src/mswInit.ts
  templates/.gitignore
  templates/web-application/public/mockServiceWorker.js
Labels: enhancement, template, cli

#39 Remove ignoreDynamic from swc config
  package.json
  pnpm-lock.yaml
  templates/web-application/.eslintrc.json
  templates/web-application/package.json
  templates/web-application/swc.build.js
  templates/web-application/swc.dev.js
Labels: enhancement, template

#41 MSW is now optionnal and can be activate from `dev:mock` command ;; WLFE-64
  templates/web-application/package.json
  templates/web-application/src/components/TheAnswer.tsx
  templates/web-application/src/index.tsx
  templates/web-application/webpack.dev.js
Labels: enhancement, template

#42 Add step in @workleap/foundry to update template dependencies ;; WLFE-67
  .changeset/forty-scissors-cross.md
  package.json
  packages/foundry/package.json
  packages/foundry/src/create.ts
  packages/foundry/src/updateDependencies.ts
  pnpm-lock.yaml
  pnpm-workspace.yaml
  templates/web-application/package.json
  templates/web-application/src/mocks/browser.ts
  templates/web-application/src/mocks/handlers.ts
Labels: enhancement, template, cli

#44 Add SVGR support in web-application template ;; WLFE-61
  templates/web-application/package.json
  templates/web-application/src/Home.tsx
  templates/web-application/src/assets/home.svg
  templates/web-application/src/index.tsx
  templates/web-application/webpack.build.js
  templates/web-application/webpack.dev.js
Labels: enhancement, template

#49 Fix web-application Webpack cache warning ;; WLFE-69
  templates/web-application/loadSwcConfig.js
  templates/web-application/webpack.build.js
  templates/web-application/webpack.dev.js
Labels: bug

#46 Add Storybook and Chromatic support to the web-application template #35 ;; WLFE-65
  CONTRIBUTING.md
  templates/web-application/.eslintignore
  templates/web-application/.storybook/main.ts
  templates/web-application/.storybook/preview.ts
  templates/web-application/README.md
  templates/web-application/package.json
  templates/web-application/src/Home.stories.tsx
  templates/web-application/src/Home.tsx
  templates/web-application/src/NoMatch.stories.tsx
  templates/web-application/src/Office.stories.tsx
  templates/web-application/src/RootErrorBoundary.stories.tsx
  templates/web-application/src/RootErrorBoundary.tsx
  templates/web-application/src/components/Loading.stories.ts
  templates/web-application/src/components/TheAnswer.stories.ts
Labels: enhancement, template

#52 Remove src/components folder from web-app tempalte
  templates/web-application/src/App.tsx
  templates/web-application/src/Loading.stories.ts
  templates/web-application/src/Loading.test.tsx
  templates/web-application/src/Loading.tsx
  templates/web-application/src/Office.tsx
  templates/web-application/src/RootLayout.tsx
  templates/web-application/src/TheAnswer.stories.ts
  templates/web-application/src/TheAnswer.test.tsx
  templates/web-application/src/TheAnswer.tsx
  templates/web-application/src/index.tsx
Labels: bug

#57 Updated readmes
  README.md
  packages/create-project/README.md
Labels: documentation

#58 Updated contributing documentation
  CONTRIBUTING.md
Labels: documentation

#55 Updated Jest setup + fixed packaging
  jest.config.ts
  package.json
  packages/create-project/package.json
  packages/foundry/jest.config.ts
  packages/foundry/package.json
  packages/foundry/swc.jest.ts
  pnpm-lock.yaml
Labels: enhancement, build and tooling

#66 Fix text replace in binary and wrong stderr log ;; WLFE-73
  .changeset/green-houses-smash.md
  package.json
  packages/create-project/package.json
  packages/foundry/package.json
  packages/foundry/src/mswInit.ts
  packages/foundry/src/replaceTokens.ts
  packages/foundry/tests/replaceTokens.test.ts
  pnpm-lock.yaml
Labels: bug, enhancement
